apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-demo
nameSuffix: -demo

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images-prod/hello-world
  newTag: 0d0d5485e2d4d32a8e3f57da6e65470b08bc60dc

commonLabels:
  env: demo
