apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-demo
nameSuffix: -demo

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images-prod/hello-world
  newTag: a704f462bc20992be519bda4d53706c4ef0ab4c5-38

commonLabels:
  env: demo
