# Do not touch key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: c357052c72b52508c8dd8881ea91314cfcf0d342
project: markbox-cts
service_accounts:
  - hello-world-app-dev
buckets:
  - name: hello-world-dev
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-dev
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
