# Do NOT touch key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: 2b6b34b45f62b7bc7ac9c96d36972e7be30d8cda
project: markbox-cts
service_accounts:
  - hello-world-app-dev
buckets:
  - name: hello-world-dev
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-dev
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
