# Do NOT touch key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: 4c9f523aeb096a1389c6207cf95b5291a41233cc
project: markbox-cts
service_accounts:
  - hello-world-app-dev
buckets:
  - name: hello-world-dev
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-dev
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-dev@markbox-cts.iam.gserviceaccount.com"
