# Do NOT touch key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: e3db987aeb45afc9ed062efdabbb33f230cd132b
project: markbox-cts
service_accounts:
  - hello-world-app-live
buckets:
  - name: hello-world-live
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-live@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-live
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-live@markbox-cts.iam.gserviceaccount.com"
