# Do NOT touch the key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: d02972ae6d03b47aa62b59ea374ed9bfd238ad7b
project: markbox-cts
service_accounts:
  - hello-world-app-uat
buckets:
  - name: hello-world-uat
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-uat@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-uat
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-uat@markbox-cts.iam.gserviceaccount.com"
