# Do not touch key auto_module_versions: managed by GHA
auto_module_versions:
  project: 05cfc5701d2a9f3afaf0099b0672a48d4e1ef5a8
  bucket: 2df43ae7ed2d9aa970ba808c4e2573eab469f8f5
project: markbox-cts
service_accounts:
  - hello-world-app-uat
buckets:
  - name: hello-world-uat
    location: EU
    force_destroy: true
iam:
  - kind: Project
    bindings:
      "roles/viewer":
        - "serviceAccount:hello-world-app-uat@markbox-cts.iam.gserviceaccount.com"
  - kind: StorageBucket
    resource: hello-world-uat
    bindings:
      "roles/storage.objectAdmin":
        - "serviceAccount:hello-world-app-uat@markbox-cts.iam.gserviceaccount.com"
