apiVersion: v1
kind: Service
metadata:
  labels: &Labels
    app: hello
  name: hello-world
  namespace: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector: *Labels
