apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-2
  labels: &Labels
    app: hello-2
spec:
  replicas: 1
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
      - name: hello-world-2
        image: hello-world-2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels: &Labels
    app: hello-2
  name: hello-world-2
  namespace: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector: *Labels
