apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 9621e05be76f86461ffdf9d8cb9c77f7f529a2e6
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: wrongs

commonLabels:
  env: dev
