apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 4a51ae39be546b1b256e1e613ecf992576268006
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: wrongs

commonLabels:
  env: dev
