apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: e6daff5c185bce57f60cc1521e3aec6e3b156c1c
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: wrongs

commonLabels:
  env: dev
