apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base
- alert.yaml

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: a9073bd06bad4d04f01c81fff955ed6ac5e18a7d

commonLabels:
  env: dev
