apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base
- ingress.yaml

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 28936882a1840b8451dec508b5697a1808a53536-41

commonLabels:
  env: dev
  team: breakfast
