apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-dev
nameSuffix: -dev

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 6c7715a1f16da787defb065a5f987624aad04d45
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: wrongs

commonLabels:
  env: dev
