apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-uat
nameSuffix: -uat

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: a5fba481bd6f56f9cf3a29b1ee0b251951730872
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 54607f42a4598d389b9e890b1b62e894d16fefa6

commonLabels:
  env: uat
