apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-uat
nameSuffix: -uat

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 795ad4c09f21480fa027471e459ddf4843d50722

commonLabels:
  env: uat
