name: Terraform Dev Apply
on:
  push:
    branches:
      - main
    paths:
      - infra/tf/terraform/**
jobs:
  apply:
    runs-on: ubuntu-latest
    name: "Terraform Apply"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.31.4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/key.json
    
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            infra/tf/terraform/**
      - id: set-matrix
        run: |
          IFS=$'\n'
          x="${{ steps.changed-files-specific.outputs.all_changed_and_modified_files }}"
          echo $x
          for direct in $x
          do
                  dirname=$(dirname -- ${direct})
                  echo "$(basename ${dirname})" >> list
          done
          LIST=$(cat list | uniq)
          rm list
          echo $LIST
          echo "::set-output name=matrix::$LIST"
      - name: Terragrunt Apply
        id: apply
        run: |
          echo "Running Apply"
          cd infra/tf/
          TG_ENVIRONMENT=dev terragrunt run-all apply -auto-approve --terragrunt-working-dir terraform/ --terragrunt-include-external-dependencies --terragrunt-non-interactive
      - name: Terragrunt Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1
      - name: Set yaml for UAT
        run: |
          export list="${{ steps.set-matrix.outputs.matrix }}"
          export SHA="${{ github.event.pull_request.head.sha }}"
          for mod in $list
          do
              MODULENAME=$mod yq e '.auto_module_versions[strenv(MODULENAME)] |= strenv(SHA)' infra/tf/environments/uat.yaml
              MODULENAME=$mod yq e '.auto_module_versions[strenv(MODULENAME)] |= strenv(SHA)' -i infra/tf/environments/uat.yaml
          done
      - name: commit uat
        uses: EndBug/add-and-commit@v7
        with:
          add: infra/tf/environments/uat.yaml
          author_name: "ci"
          author_email: "ci@gingerninja.co"
          message: "Deploy changes to UAT from ${{ github.event.pull_request.head.sha }}"
          push: false
      - name: Create PR
        id: pr-uat
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main # branch to merge into
          commit-message: Deploy changes to UAT from ${{ github.event.pull_request.head.sha }}
          committer: ci <ci@gingerninja.co>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: tf-uat
          delete-branch: true
          title: '[CI] Deploy changes to UAT from ${{ github.event.pull_request.head.sha }}'
          body: |
            *Automated PR*
            This PR is created by CI

            Deploying ${{ github.event.pull_request.head.sha }} to UAT
          labels: |
            automated
          assignees: Bltt
          reviewers: mark-cts
          team-reviewers: |
            owners
          draft: false
