---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-sa
  namespace: flux-system
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flux-system
  name: gha-sa
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "status", "describe"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-sa-rb
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: gha-sa
  namespace: flux-system
roleRef:
  kind: Role
  name: gha-sa
  apiGroup: rbac.authorization.k8s.io