apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-live
nameSuffix: "-live"

resources:
  - ../../base

images:
  - name: hello-world-img
    newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world-img
    newTag: "imthegitsha"

commonLabels:
  env: live
