apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-live
nameSuffix: -live

resources:
- ../../base

images:
- name: hello-world
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: b9956d023a6fe30375f20c9b362bc886fece2113
- name: hello-world-2
  newName: europe-west1-docker.pkg.dev/markbox-cts/images/hello-world
  newTag: 54607f42a4598d389b9e890b1b62e894d16fefa6

commonLabels:
  env: live
