name: live

on:
  status
env:
  IMAGE: hello-world
  REGISTRY_HOSTNAME: europe-west1-docker.pkg.dev/markbox-cts/images
  PROD_REGISTRY_HOSTNAME: europe-west1-docker.pkg.dev/markbox-cts/images-prod
  PROJECT_ID: markbox-cts
  ENVIRONMENT_PREV: uat
  ENVIRONMENT: live

jobs:
  update-live:
    name: Update Live Image
    environment: live
    if: github.event.state == 'success' && github.event.commit.commit.author.name == 'ci' && contains(github.event.commit.commit.message, 'uat') && github.event.context == 'kustomization/hello-world-uat' # kustomize/dep-name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - name: set image
        run: |
          export IMAGE_TAG=$(yq e '.images' infra/k8s/overlays/${{ env.ENVIRONMENT_PREV }}/kustomization.yaml -o=json | jq -r ".[] | select(.name==\"${{ env.IMAGE }}\") | .newTag")
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          cd infra/k8s/overlays/${{ env.ENVIRONMENT }}/
          kustomize edit set image ${{ env.IMAGE }}=${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE }}:$IMAGE_TAG
          kustomize build .
      # setup gcloud for gcr auth
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: login
        uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Push Image to prod from nonprod
        run: |
          docker pull "${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          docker tag "${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" "${{ env.PROD_REGISTRY_HOSTNAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          docker push "${{ env.PROD_REGISTRY_HOSTNAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
      - name: commit
        uses: EndBug/add-and-commit@v7
        with:
          add: infra/k8s/overlays/${{ env.ENVIRONMENT }}/kustomization.yaml
          author_name: "ci"
          author_email: "ci@gingerninja.co"
          message: "Set image for ${{ env.IMAGE }} in ${{ env.ENVIRONMENT }} to ${{ env.IMAGE_TAG }}"
          push: false      
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main # branch to merge into
          commit-message: Deploy changes to live from uat
          committer: ci <ci@gingerninja.co>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: app-${{ env.next_env }}
          delete-branch: true
          title: '[CI] Deploy changes to live from uat'
          body: |
            *Automated PR*

            This PR is to deploy changes to live from uat
          labels: |
            automated
            infra
          assignees: Bltt
          reviewers: mark-cts
          team-reviewers: |
            owners
          draft: false
