name: App Deploy Live
on: 
  push:
    branches:
      - main
    paths:
      - infra/k8s/overlays/live/**
env:
  PROJECT_ID: markbox-cts
  ENV: live
  APP_NAME: hello-world
  CLUSTER_NAME: tester
  CLUSTER_REGION: europe-west1
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: azure/setup-kubectl@v1
      - uses: imranismail/setup-kustomize@v1
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/key.json
      - name: get-gke-creds
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_REGION }}
      - name: check
        run: |
          newsha=$(kubectl get -n flux-system kustomization/${{ env.APP_NAME }}-${{ env.ENV }} -o=jsonpath='{.status.lastAppliedRevision}' | cut -d "/" -f 2)
          git pull
          commitshort="${{ env.GITHUB_SHA }}"
          sha="$(git rev-parse ${commitshort})"
          if [[ "$sha" == "" ]]
          then
                  sha="$(git rev-parse HEAD)"
          fi
          echo "Cluster currently has ${newsha} deployed."
          echo "Waiting for ${sha} to be deployed."
          echo "Cluster : Git"
          counter=0
          until [[ "$newsha" == "$sha" || $counter -gt 120 ]] # 120x5 == 10mins
          do
                  echo "Compared: $newsha : $sha"
                  newsha=$(kubectl get -n flux-system kustomization/${{ env.APP_NAME }}-${{ env.ENV }} -o=jsonpath='{.status.lastAppliedRevision}' | cut -d "/" -f 2)
                  echo "Not yet synced. Waiting for 5s.."
                  sleep 5
                  counter=$(($counter+1))
          done
          if [[ $counter -gt 120 ]]
          then
                  echo ""
                  echo "*Deployment failed. Requires investigation.*"
                  # look at rollback here
          else
                  echo "Reconcile Complete"
          fi
          kubectl wait -n flux-system kustomization/${{ env.APP_NAME }}-${{ env.ENV }} --for=condition=healthy --timeout=5m
        # Add rollback here
        # add integration tests here too
