name: K8S Linting
on:
  pull_request:
    branches:
      - main
    paths:
      - infra/k8s/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*infra/k8s/.*
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get changed envs
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            infra/k8s/base
            infra/k8s/overlays/dev
            infra/k8s/overlays/uat
            infra/k8s/overlays/demo
            infra/k8s/overlays/live      
      - id: set-matrix
        run: |
          CHANGED_ENVFILES_IN_COMMIT="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          echo $CHANGED_ENVFILES_IN_COMMIT
          matrix=$(jq -c -n --arg inarr "$CHANGED_ENVFILES_IN_COMMIT" '{ plans: $inarr | split(" ") }')
          echo $matrix
          echo $matrix | jq .plans
          echo "::set-output name=matrix::$matrix"
  test:
    name: Lint
    runs-on: ubuntu-latest    
    needs: lint
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.lint.outputs.matrix)}}
    steps:
      - uses: imranismail/setup-kustomize@v1
      - name: Set Env
        run: |
          env=$(basename ${{ matrix.plans }} | cut -f 1 -d '.')
          ENV=${env^^}
          echo "ENVIRONMENT=$ENV" >> $GITHUB_ENV
      - name: kustomize build
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          env=$(basename ${{ matrix.plans }} | cut -f 1 -d '.')
          cd infra/k8s/overlays/${{ env.ENVIRONMENT }}/
          kustomize build .
# todo: add lint step for justomize build, dry runs etc. need to work out env to get correct paths etc
