name: K8S Linting
on:
  pull_request:
    branches:
      - main
    paths:
      - infra/k8s/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      # - name: Lint Code Base
      #   uses: github/super-linter@v4
      #   env:
      #     VALIDATE_ALL_CODEBASE: false
      #     FILTER_REGEX_INCLUDE: .*infra/k8s/.*
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get changed envs
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            infra/k8s/base
            infra/k8s/overlays/dev
            infra/k8s/overlays/uat
            infra/k8s/overlays/demo
            infra/k8s/overlays/live 
      - id: set-matrix
        run: |
          CHANGED_ENVFILES_IN_COMMIT="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          echo $CHANGED_ENVFILES_IN_COMMIT
          y=($CHANGED_ENVFILES_IN_COMMIT)
          changed=()
          for direct in ${y[@]}
          do
            DIR=$(dirname ${direct})
            changed+=( $(basename ${DIR}) )
          done
          LIST=${changed[@]}
          LIST=$(echo $LIST | xargs -n1 | sort -u | xargs | sed "s# # #g" ) # sort it to avoid duplicates
          matrix=$(jq -c -n --arg inarr "$LIST" '{ plans: $inarr | split(" ") }')
          echo "matrix $matrix"
          echo "::set-output name=matrix::$matrix"
  test:
    name: Lint
    runs-on: ubuntu-latest    
    needs: lint
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.lint.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - name: kustomize build
        run: |
          ENV=$(echo ${{ matrix.plans }} | cut -f 4 -d '/')
          if [[ "$ENV" == "base" ]]
          then
            cd infra/k8s/base
          else
            cd infra/k8s/overlays/$ENV/
          fi
          kustomize build .
# todo: add lint step for justomize build, dry runs etc. need to work out env to get correct paths etc
