name: Terraform Code Change
on:
  pull_request:
    paths:
      - infra/tf/terraform/**
concurrency:
  group: tf-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  commit-dev:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'ci'
    name: "Validate and Commit Dev versions"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.31.4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/key.json

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            infra/tf/terraform/**
      - id: set-matrix
        name: sort files
        run: |
          IFS=$'\n'
          x="${{ steps.changed-files-specific.outputs.all_changed_and_modified_files }}"
          echo $x
          for direct in $x
          do
                  dirname=$(dirname -- ${direct})
                  echo "$(basename ${dirname})" >> list
          done
          LIST=$(cat list | uniq)
          rm list
          echo $LIST
          echo "::set-output name=matrix::$LIST"
      - name: Set yaml for DEV
        run: |
          export list="${{ steps.set-matrix.outputs.matrix }}"
          export SHA="${{ github.event.pull_request.head.sha }}"
          for mod in $list
          do
              echo "changing $mod"
              MODULENAME=$mod yq e '.auto_module_versions[strenv(MODULENAME)] |= strenv(SHA)' -i infra/tf/environments/dev.yaml
          done
      - name: commit dev
        uses: EndBug/add-and-commit@v7
        with:
          add: infra/tf/environments/dev.yaml
          author_name: "ci"
          author_email: "ci@gingerninja.co"
          message: "Deploy changes to dev from ${{ github.event.pull_request.head.sha }}"
      - name: Terragrunt Validate
        id: validate
        run : |
          cd infra/tf/
          echo "Validating"
          TG_ENVIRONMENT=dev terragrunt run-all validate -no-color --terragrunt-working-dir terraform/ --terragrunt-include-external-dependencies --terragrunt-non-interactive
      - name: Terragrunt Validate Status
        if: steps.validate.outcome == 'failure'
        run: exit 1

