name: Terraform Config
on:
  push:
    branches:
      - main
    paths:
      - infra/tf/environments/**
  pull_request:
    paths:
      - infra/tf/environments/**
  workflow_run:
    workflows: ["Terraform Dev Update"]
    types:
      - completed
env:
  # to track the next env
  after_dev: uat
  after_uat: live
  after_live: demo
  after_demo: nil
jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Compile Updated/New Environment files
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed envs
        id: changed-files-specific
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            infra/tf/environments/*yaml
      - id: set-matrix
        run: |
          IFS=$'\n'
          x="${{ steps.changed-files-specific.outputs.all_changed_and_modified_files }}"
          echo $x
          matrix=$(jq -c -n --arg inarr "$x" '{ plans: $inarr | split(" ") }')
          echo $matrix
          echo $matrix | jq .plans
          echo "::set-output name=matrix::$matrix"
  check-matrix:
    runs-on: ubuntu-latest
    name: Test JSON
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml
      - name: Check matrix definition
        run: |
          matrix='${{needs.matrix.outputs.matrix}}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  backend:
    runs-on: ubuntu-latest
    needs: matrix
    name: "Terragrunt run on ${{ matrix.plans }}"
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.31.4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/key.json

      - name: Terragrunt Validate
        id: validate
        run : |
          filename=$(basename ${{ matrix.plans }} | cut -f 1 -d '.' )
          cd infra/tf/
          echo "Validating for $filename"
          TG_ENVIRONMENT=$filename terragrunt run-all validate -no-color --terragrunt-working-dir terraform/ --terragrunt-include-external-dependencies --terragrunt-non-interactive
      # plan only
      - name: Terragrunt Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          filename=$(basename ${{ matrix.plans }} | cut -f 1 -d '.' )
          cd infra/tf/
          echo "Running plan for $filename"
          TG_ENVIRONMENT=$filename terragrunt run-all plan -no-color --terragrunt-working-dir terraform/ --terragrunt-include-external-dependencies --terragrunt-non-interactive
        continue-on-error: true
      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Validation for ${{ matrix.plans }} 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan for ${{ matrix.plans }}📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${{ env.PLAN }}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terragrunt Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      # apply only
      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          filename=$(basename ${{ matrix.plans }} | cut -f 1 -d '.' )
          echo "Running Apply for $filename"
          cd infra/tf/
          TG_ENVIRONMENT=$filename terragrunt run-all apply -auto-approve --terragrunt-working-dir terraform/ --terragrunt-include-external-dependencies --terragrunt-non-interactive
      - name: Terragrunt Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1
      # make PR On next env
      - name: update next environment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |          
          export cur_env=$(basename ${{ matrix.plans }} | cut -f 1 -d '.' )
          eval next_env='$'after_$cur_env
          echo "next_env=$next_env" >> $GITHUB_ENV
          echo "c: $cur_env - n: $next_env"
          VAL=$(yq e '.auto_module_versions' infra/tf/environments/${cur_env}.yaml) yq e '.auto_module_versions |= env(VAL)' -i infra/tf/environments/${next_env}.yaml
          VAL=$(yq e '.auto_module_versions' infra/tf/environments/${cur_env}.yaml) yq e '.auto_module_versions |= env(VAL)' infra/tf/environments/${next_env}.yaml
      - name: commit ${{ matrix.plans }}
        id: commit
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: EndBug/add-and-commit@v7
        with:
          add: infra/tf/environments/${{ env.next_env }}.yaml
          author_name: "ci"
          author_email: "ci@gingerninja.co"
          message: "Deploy changes to ${{ env.next_env }} from ${{ env.cur_env }}"
          push: false
      - name: Commit Status
        if: steps.commit.outputs.commit == false
        run: exit 1
      - name: Create PR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main # branch to merge into
          commit-message: Deploy changes to ${{ env.next_env }} from ${{ env.cur_env }}
          committer: ci <ci@gingerninja.co>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: tf-${{ env.next_env }}
          delete-branch: true
          title: '[CI] Deploy changes to ${{ env.next_env }} from ${{ env.cur_env }}'
          body: |
            *Automated PR*
            This PR is created by CI

            Deploy changes to ${{ env.next_env }} from ${{ env.cur_env }}
          labels: |
            automated
          assignees: Bltt
          reviewers: mark-cts
          team-reviewers: |
            owners
          draft: false

        
